# Generated by Django 4.1.5 on 2024-01-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMaster',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CourtEstablishmentMaster',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategoryMaster',
            fields=[
                ('product_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('Consumable', 'Consumable'), ('Non-Consumable', 'Non-Consumable')], max_length=20, verbose_name='Product Type')),
                ('product_cat_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCompanyMaster',
            fields=[
                ('product_com_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_com_name', models.CharField(max_length=250)),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productcategorymaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_serialno', models.CharField(default='None', editable=False, max_length=250)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('initial_quantity', models.IntegerField(default=1, editable=False)),
                ('current_quantity', models.IntegerField()),
                ('cartridge_toner', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=300)),
                ('product_new_or_open', models.CharField(default='NEW', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('billmemono', models.CharField(max_length=50)),
                ('purchased_by', models.CharField(choices=[('High Court Bilashpur', 'High Court Bilashpur'), ('District Court Durg', 'District Court Durg')], max_length=50)),
                ('purchased_for', models.CharField(choices=[('District Court Durg', 'DCD'), ('District Court Durg-POCSO', 'DCD_POCSO'), ('District Court Durg-SPECIAL', 'DCD_SP')], max_length=50)),
                ('purchase_remarks', models.CharField(max_length=350)),
                ('billmemodoc', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='staffDesignationMaster',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_des_name', models.CharField(max_length=250)),
                ('staff_type', models.CharField(choices=[('Court', 'Court'), ('Section', 'Section')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=250)),
                ('usr_mobile', models.CharField(max_length=250)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('usr_type', models.CharField(choices=[('Judge', 'Judge'), ('Staff', 'Staff')], max_length=10)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SectionDetails',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('Court', 'Court'), ('Section', 'Section')], max_length=10)),
                ('section_name', models.CharField(max_length=250)),
                ('floor', models.CharField(default='', max_length=250)),
                ('roomno', models.CharField(default='', max_length=250)),
                ('landmark', models.CharField(default='', max_length=250)),
                ('deleted', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.buildingmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SectionDesignationMapper',
            fields=[
                ('sdm_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sectiondetails')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.staffdesignationmaster')),
            ],
        ),
        # migrations.CreateModel(
        #     name='ProductTransactionDetails',
        #     fields=[
        #         ('pro_trans_id', models.AutoField(primary_key=True, serialize=False)),
        #         ('issue_date', models.DateField()),
        #         ('no_of_item_issue', models.IntegerField()),
        #         ('issue_remarks', models.CharField(max_length=250)),
        #         ('return_date', models.DateField()),
        #         ('no_of_item_return', models.IntegerField(default=0)),
        #         ('return_remarks', models.CharField(default='', max_length=250)),
        #         ('trans_flag', models.CharField(max_length=2)),
        #         ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productdetails')),
        #         ('sdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sectiondesignationmapper')),
        #     ],
        # ),
        migrations.CreateModel(
            name='ProductPuchaseDetails',
            fields=[
                ('propur_id', models.AutoField(primary_key=True, serialize=False)),
                ('propur_remarks', models.CharField(max_length=350)),
                ('box_detail', models.CharField(max_length=350)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchasedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModelMaster',
            fields=[
                ('product_mod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_mod_name', models.CharField(max_length=250)),
                ('product_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productcompanymaster')),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_mod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productmodelmaster'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='propur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.productpuchasedetails'),
        ),
        migrations.CreateModel(
            name='HealthStatusDetails',
            fields=[
                ('health_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_healthy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10)),
                ('health_remarks', models.CharField(default='New Product', max_length=250)),
                ('product_status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working')], default='Working', max_length=50)),
                ('status_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Journey',
            fields=[
                ('emp_jou_id', models.AutoField(primary_key=True, serialize=False)),
                ('doj', models.DateField()),
                ('dot', models.DateField()),
                ('current_status', models.CharField(choices=[('Deputed', 'Deputed'), ('Transfered', 'Transfered'), ('Vacant', 'Vacant')], default='V', max_length=10)),
                ('sdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sectiondesignationmapper')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.userdetails')),
            ],
        ),
        migrations.AddField(
            model_name='buildingmaster',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.courtestablishmentmaster'),
        ),
    ]
