# Generated by Django 4.1.5 on 2024-01-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiondesignationmapper',
            name='ip_address',
            field=models.CharField(default='', max_length=250),
        ),
    ]
