# Generated by Django 4.1.5 on 2024-01-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sectiondesignationmapper_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpuchasedetails',
            name='box_detail',
            field=models.FileField(upload_to='productBoxDetails/'),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='billmemodoc',
            field=models.FileField(upload_to='BillMemo/'),
        ),
    ]
