# Generated by Django 4.1.5 on 2024-01-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productpuchasedetails_box_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpuchasedetails',
            name='no_of_item',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='productpuchasedetails',
            name='product',
            field=models.ForeignKey(default=96, on_delete=django.db.models.deletion.CASCADE, to='inventory.productmodelmaster'),
        ),
    ]
