# Generated by Django 4.1.5 on 2024-02-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productpuchasedetails_no_of_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_journey',
            name='dot',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='productpuchasedetails',
            name='no_of_item',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='productpuchasedetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productmodelmaster'),
        ),
    ]
