# Generated by Django 4.1.5 on 2024-02-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_employee_journey_dot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnallocatedUsers',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=250)),
                ('usr_mobile', models.CharField(max_length=250)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('usr_type', models.CharField(choices=[('Judge', 'Judge'), ('Staff', 'Staff')], max_length=10)),
            ],
            options={
                'db_table': 'unallocatedusers',
                'managed': False,
            },
        ),
    ]
