# Generated by Django 4.1.5 on 2024-02-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_secdesview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secdesview',
            options={'managed': False},
        ),
    ]
