# Generated by Django 4.1.5 on 2024-02-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_secdesview_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='secdesview',
            table='secdesview',
        ),
    ]
