# Generated by Django 4.1.5 on 2024-08-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_secdesview_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_journey',
            name='verified',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_new_or_open',
            field=models.CharField(default='NEW PRODUCT', max_length=7),
        ),
    ]
