# Generated by Django 4.1.5 on 2024-11-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_employee_journey_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_journey',
            name='pawatidoc',
            field=models.FileField(default='', upload_to='Pawati/'),
        ),
    ]
